# Generated by Django 5.0.6 on 2024-06-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_justuser_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='number',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(default='123', max_length=12),
            preserve_default=False,
        ),
    ]
