# Generated by Django 5.0.6 on 2024-06-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_category_alter_product_options_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
