# Generated by Django 5.0.6 on 2024-06-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_status_orderitem_price_at_purchase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='date_purchased',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
