# Generated by Django 5.0.6 on 2024-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_date_purchased_purchasehistory_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
