# Generated by Django 5.0.6 on 2024-06-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_delivered_time_order_processing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
