# Generated by Django 5.0.6 on 2024-06-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_customer_default_address_customer_default_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='default_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_zipcode',
        ),
    ]
