# Generated by Django 5.0.6 on 2024-06-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_customer_default_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='whatsapp',
            field=models.CharField(default='9876543210', max_length=12),
            preserve_default=False,
        ),
    ]
