# Generated by Django 5.0.6 on 2024-06-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_shippingaddress_whatsapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='active',
        ),
    ]
