# Generated by Django 5.0.6 on 2024-07-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_customer_email_customer_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
