# Generated by Django 5.0.6 on 2024-07-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='intro_images/')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
