# Generated by Django 5.0.6 on 2024-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
