# Generated by Django 5.1.1 on 2024-09-18 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_product_options_alter_product_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'category', 'verbose_name_plural': 'categorys'},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
