# Generated by Django 5.1.1 on 2024-10-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_category_options_category_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='date_added',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='discounted_price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='shipping_charge_at_purchase',
            field=models.DecimalField(decimal_places=2, default='99', max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='subtotal_at_purchase',
            field=models.DecimalField(decimal_places=2, default='199', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
