# Generated by Django 5.1.1 on 2024-10-06 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='discounted_price_at_purchase',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='shipping_charge_at_purchase',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='subtotal_at_purchase',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='Shipping_cost',
            field=models.DecimalField(decimal_places=0, default='88', max_digits=7),
            preserve_default=False,
        ),
    ]
