# Generated by Django 5.1.1 on 2024-10-07 17:15

from django.db import migrations
import uuid

def generate_order_id(apps, schema_editor):
    Order = apps.get_model('store', 'Order')
    for order in Order.objects.filter(order_id__isnull=True):
        order.order_id = str(uuid.uuid4())
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_add_order_id_field'),  # replace #### with the actual migration number
    ]

    operations = [
        migrations.RunPython(generate_order_id),
    ]
